version: 2.0
jobs:
 build:
   working_directory: /sunder
   docker:
     - image: docker:18.03.1-ce-git
   steps:
     - checkout
     - setup_remote_docker
     - restore_cache:
         keys:
           - v1-{{ .Branch }}
         paths:
           - /caches/sunder.tar
     - run:
         name: Load Docker image layer cache
         command: |
           set +o pipefail
           docker load -i /caches/sunder.tar | true
     - run:
         name: Build Docker image
         command: |
           docker build --cache-from=sunder-build -t sunder-build .
     - run:
         name: Save Docker image layer cache
         command: |
           mkdir -p /caches
           docker save -o /caches/sunder.tar sunder-build
     - save_cache:
         key: v1-{{ .Branch }}-{{ epoch }}
         paths:
           - /caches/sunder.tar
     - run:
         name: Create a volume with a copy of the repository
         command: |
           # create a dummy container which will hold a volume with the repo
           docker create -v /sunder --name sunder-repo alpine:3.4 /bin/true
           # ensure this volume belongs to the 'node' user id in sunder-build
           chown -R 1000 /sunder
           # copy the repo into this volume
           docker cp /sunder sunder-repo:/
     - run:
         name: Build and package
         command: |
           docker run --volumes-from sunder-repo sunder-build:latest tools/build-sunder-debian-packages.sh
     - run:
         name: Test
         command: |
           # start an application container using this volume
           docker run --volumes-from sunder-repo sunder-build:latest tools/docker-test.sh
     - run:
         name: Lint docs
         command: |
           docker run --volumes-from sunder-repo sunder-build:latest make docs-lint
