version: 2.0
jobs:
 build:
   docker:
     - image: liliakai/sunder-build:latest
   steps:
     - checkout
     - run:
         name: npm install and build RustySecrets
         command: |
           # Hack to unbreak cargo fetching (we need HTTPS, not SSH URLs).
           rm -f ~/.gitconfig
           # Hack to force sourcing of rust env
           source ~/.cargo/env
           npm install
     - run:
         name: Run unit tests and e2e tests
         command: xvfb-run --server-args=$XVFB_ARGS make test
     - run:
         name: Build docs
         command: make docs-lint
